### Register user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "Ahmed",
    "email": "ahmed@example.com",
    "password": "password123"
}

### Login user
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "ahmed@example.com",
    "password": "password123"
}

### Get current Profile
GET http://localhost:5000/api/auth/me
Authorization:Bearer YOUR_ACCESS_TOKEN
