### Get project members
GET http://localhost:5000/api/projects/1/members
Authorization: Bearer YOUR_ACCESS_TOKEN
Content-Type: application/json

### Add project member
POST http://localhost:5000/api/projects/4/members
Authorization: Bearer YOUR_ACCESS_TOKEN
Content-Type: application/json

{
  "email": "james@example.com"
}

### Delete project member
DELETE http://localhost:5000/api/projects/1/members/2
Authorization: Bearer YOUR_ACCESS_TOKEN
Content-Type: application/json